kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    commands:
      - pwd
      - cp /home/imaoplab/secret/.env .
      - cp /home/imaoplab/secret/pendown-firebase.json .
      - docker build -t pendown-be .

  - name: run
    commands:
      - docker rm -f pd-be
      - docker run -d -p 8080:8080 --name pd-be pendown-be
